/* Auto-generated by golden_model.py -- DO NOT EDIT */
#ifndef GOLDEN_EXPECTED_H
#define GOLDEN_EXPECTED_H

#include <stdint.h>

typedef struct {
    uint16_t M, K, N;
    uint8_t  pattern;   /* 0=seq, 1=ones, 2=ident, 3=max */
    uint32_t checksum;  /* sum of all output bytes as uint32 */
    uint8_t  c00;       /* expected C[0][0] */
} golden_test_t;

#define NUM_GOLDEN_TESTS 21

static const golden_test_t golden_tests[NUM_GOLDEN_TESTS] = {
    {   1,   1,   1, 0, 0x00000000, 0x00 },  /* # 1: 1x1x1 trivial */
    {   2,   2,   2, 0, 0x000000F2, 0x15 },  /* # 2: 2x2x2 tiny */
    {   3,   3,   3, 0, 0x00000506, 0x69 },  /* # 3: 3x3x3 small odd */
    {   4,   4,   4, 0, 0x000007D0, 0x26 },  /* # 4: 4x4x4 sub-tile */
    {   5,   5,   5, 0, 0x00000BD2, 0x76 },  /* # 5: 5x5x5 non-aligned */
    {   7,   7,   7, 0, 0x00001968, 0x77 },  /* # 6: 7x7x7 near boundary */
    {   8,   8,   8, 0, 0x00001C80, 0x7C },  /* # 7: 8x8x8 exact tile */
    {   9,   9,   9, 0, 0x000028EC, 0xBC },  /* # 8: 9x9x9 over one tile */
    {  15,  15,  15, 0, 0x00006C94, 0x43 },  /* # 9: 15x15x15 multi-tile */
    {  16,  16,  16, 0, 0x00007F00, 0xB8 },  /* #10: 16x16x16 exact multi-tile */
    {   1,   8,   1, 0, 0x0000007C, 0x7C },  /* #11: 1x8x1 single row/col */
    {   8,   1,   8, 0, 0x00001950, 0x00 },  /* #12: 8x1x8 single K */
    {   3,   5,   7, 0, 0x0000097D, 0x76 },  /* #13: 3x5x7 non-square */
    {   7,   9,   3, 0, 0x00000A5F, 0xBC },  /* #14: 7x9x3 non-square multi-K */
    {   1,  16,   1, 0, 0x000000B8, 0xB8 },  /* #15: 1x16x1 long K */
    {   8,   8,   8, 1, 0x00000200, 0x08 },  /* #16: 8x8x8 all-ones */
    {   8,   8,   8, 2, 0x000008C0, 0x00 },  /* #17: 8x8x8 identity A */
    {   4,   4,   4, 3, 0x00000040, 0x04 },  /* #18: 4x4x4 max values */
    {   8,   8,   8, 0, 0x00001C80, 0x7C },  /* #19: 8x8x8 back-to-back */
    {  16,   8,  16, 0, 0x00007A00, 0x7C },  /* #20: 16x8x16 wide multi-tile */
    {   8,  16,   8, 0, 0x00002000, 0xB8 },  /* #21: 8x16x8 tall K multi-tile */
};

#endif /* GOLDEN_EXPECTED_H */
